- id: doi:10.1101/2023.06.28.546898
  type: preprint
  image: https://user-images.githubusercontent.com/8975841/250271905-4eed44ba-528a-4a61-a4ec-fa90d51e61f9.jpg
  tags:
      - reproducibility
      - genetics
      - dogs
      
- id: url:https://icbo-conference.github.io/icbo2022/papers/ICBO-2022_paper_1882.pdf
  type: conference paper
  image: https://user-images.githubusercontent.com/8975841/260512613-910f7bcd-2648-48db-8874-d37bca58c8f1.png
  title: Classifying animal breeds with the vertebrate breed ontology (VBO)
  authors:
      - Sabrina Toro
      - Nicolas Matentzoglu
      - Kathleen R. Mullen
      - Nicole Vasilevsky
      - Halie M. Rando
      - Melissa Haendel
      - Christopher J. Mungall
      - Zhi-Liang Hu
      - Gregoire Leroy
      - Imke Tammen
      - Frank W. Nicholas
  publisher: Proceedings of the International Conference on Biomedical Ontology 
  date: "2022-09-25"
  tags:
    - ontology
    - animals
    - domestication

- id: doi:10.1016/j.ebiom.2021.103722
  type: journal paper
  image: https://www.medrxiv.org/content/medrxiv/early/2021/06/29/2021.06.23.21259416/F1.large.jpg?width=800&height=600&carousel=1
  tags:
      - ontology
      - disease
      - humans

- id: url:http://ceur-ws.org/Vol-2976/paper-2.pdf
  type: conference paper
  image: https://user-images.githubusercontent.com/8975841/137757668-cf24b018-5539-4969-965f-305fee56b2d3.png
  title: An Open-Publishing Response to the COVID-19 Infodemic
  authors:
    - Halie M. Rando
    - Simina M. Boca
    - Lucy D'Agostino McGowan
    - Daniel S. Himmelstein
    - Michael P. Robson
    - Vincent Rubinetti
    - Ryan Velazquez
    - Casey S. Greene
    - Anthony Gitter
  publisher: Digital Infrastructures for Scholarly Content Objects 2021
  date: "2021-09-30"
  tags:
    - manubot
    - reproducibility
    - documents
- id: doi:10.1128/mSystems.00122-21
  image: https://greenelab.github.io/covid19-review/images/N000-overview.png
  tags:
      - manubot
      - COVID-19
- id: doi:10.1128/msystems.00095-21 
  image: https://greenelab.github.io/covid19-review/images/N000-overview.png
  tags:
      - manubot
      - COVID-19
- id: doi:10.1128/mSystems.00233-21
  image: https://greenelab.github.io/covid19-review/images/N000-overview.png
  tags:
      - manubot
      - COVID-19
- id: doi:10.48550/ARXIV.2204.12598  
  image: https://greenelab.github.io/covid19-review/images/N000-overview.png
  tags:
      - manubot
      - COVID-19
- id: doi:10.1128/msystems.00927-22 
  image: https://greenelab.github.io/covid19-review/images/N000-overview.png
  tags:
      - manubot
      - COVID-19
- id: doi:10.1128/msystems.00928-22 
  image: https://greenelab.github.io/covid19-review/images/N000-overview.png
  tags:
      - manubot
      - COVID-19
- id: doi:10.1101/2021.03.20.21253896
  image: https://user-images.githubusercontent.com/8975841/112666874-013a3400-8e33-11eb-9be9-5c74f3e397ea.png
  type: preprint
  tags:
      - ontology
      - disease
      - humans
- id: doi:10.3390/genes10060409 
  image: images/thumbnails/Red_fox_ychromosome_genes10060409.png
  tags:
      - foxes
      - genomes
      - machine learning
- id: doi:10.3390/genes12010097
  image: https://private-user-images.githubusercontent.com/8975841/311328271-9f9e1e1f-9c37-481b-b115-b108b1712e10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjI0NzAsIm5iZiI6MTcwOTkyMjE3MCwicGF0aCI6Ii84OTc1ODQxLzMxMTMyODI3MS05ZjllMWUxZi05YzM3LTQ4MWItYjExNS1iMTA4YjE3MTJlMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMTgyMjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmJmZTQ5N2IwYTRmZWMyN2YwMDAzZDdiZTBlYjk4ZmY1ZmEwOWNlZmZkMGE2ZjJkYzkzYzQ2NjY1M2Y1NGEzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6DrQlQ8e98goHz8-U3GE4LpeEUVcoU1Jrvu4YoMpdYM
  tags:
      - foxes
      - genomes
      - wildlife
- id: doi:10.1111/age.12755 
  tags:
      - foxes
      - genomes
      - dogs
      - behavior
      - domestication
- id: doi:10.1038/s41559-018-0611-6
  tags:
      - foxes
      - genomes
      - behavior
      - domestication
- id: doi:10.3390/genes9060308
  tags:
      - foxes
      - genomes
      - high-performance computing
- id: doi:10.1002/ece3.3583
  tags:
      - foxes
      - genomes
      - wildlife
- id: doi:10.1093/jhered/esx066
  tags: 
      - foxes
      - genomes
      - wildlife
